{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "flaskapp.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  backend:
    serviceName: {{ template "flaskapp.fullname" . }}
    servicePort: {{ .Values.service.externalPort }}
{{- end -}}
